version: '3.5'

services:
  # MariaDB container
  # https://hub.docker.com/_/mariadb/
  mariadb:
    container_name: mariadb
    image: 'mariadb:10.3'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'UTC'
    volumes:
      - '.:/docker'
      - './docker/mariadb/conf:/etc/mysql/conf.d'
      - './docker/mariadb/logs:/var/log/mysql'
      - './docker/mariadb/init:/docker-entrypoint-initdb.d'

  # memcached container
  # https://hub.docker.com/_/memcached/
  memcached:
    container_name: memcached
    image: 'memcached:1.5-alpine'
    ports:
      - '11211:11211'
    volumes:
      - '.:/docker'

  # MongoDB
  # https://hub.docker.com/_/mongo/
  mongo:
    container_name: mongo
    image: 'mongo:4.0'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - '.:/docker'
      - './docker/mongo/logs:/var/log/mongodb'

  # Redis
  # https://hub.docker.com/_/redis/
  redis:
    container_name: redis
    image: 'redis:5.0-alpine'
    ports:
      - '6379:6379'
    volumes:
      - '.:/docker'
      - './docker/redis/data:/data'
    # - './docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf'

  # Adminer
  # https://hub.docker.com/_/adminer/
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - '8080:8080'
    links:
      - 'mariadb:db'
      - 'redis:redis'
      - 'mongo:mongo'

  # mongo-express
  # https://hub.docker.com/_/mongo-express/
  mongo-express:
    container_name: mongo-express
    image: 'mongo-express:latest'
    ports:
      - '8081:8081'
    links:
      - 'mongo:mongo'

  # phpMyAdmin container
  # https://hub.docker.com/r/phpmyadmin/phpmyadmin/
  phpmyadmin:
    container_name: 'phpmyadmin'
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '8082:80'
    links:
      - 'mariadb:db'
    environment:
      PMA_USER: root
      PMA_PASSWORD: secret
